Finish html red zone
htmlacademy-adaptive/476339-pognali-20 pull request #4
Opened 2020-08-11 11:49 UTC by Palladii

2020-08-28 09:49 UTC, arctic-pie requested changes

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +  <section class="profile__card card">
Транспорт у тебя отдельным блоком и левел тоже можешь вынести в отдельный блок. В остальном на этой странице это другой блок.

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +          <h2 class="plans__country">Франция, Италия</h2>
уровень заголовков не соблюдён. У тебя выше h2 - это заголовок всего раздела

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +          <h2 class="plans__country">Франция, Италия</h2>
ну и это не заголовок)

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +            <a class="markers__btn" href="#" aria-label="шаг 1"></a>
можешь якаря повесить сюда)

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +              поездку<br>и ее предполагаемую<br>длительность.</p>
тут текст располагается в зависимости от ширины экрана, не нужны br

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                </label>
Зачем нужен заголовок внутри лейбла??

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +            <p class="form-plans">Укажите предпочтительное<br>количество попутчиков, которых<br>вы хотели бы позвать в
Почему здесь класс блока?

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +              </div>
Каждый элемент формы это всегда блок, как и кнопка. Попутчики и длительность - это один блок, использованный дважды. Чекбокс "Можно с детьми" тоже отдельный блок. И тд

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <input class="form-plans__control-checkbox" type="checkbox" name="checkbox" id="checkbox"
в name должна указываться инфа из значений. Посмотри, что у тебя форма сейчас отправляет. Какой-то чекбокс отмеченный.

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <th class="form__day-name form__day-name--red">В</th>
Что за form?

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +              <caption class="calendar__mounths">Март 2019</caption>
Переключатели месяца забыла разметить

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +            <a class="form-plans__next button" href="form.html#step-2">Следующий шаг</a>
В якорь достаточно только id указать

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +          <div class="container--narrow">
модификатор без основного класса

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +          <div class="container--narrow">
модификатор без основного класса

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +              несколько.</p>
Потеряла маркеры шагов, которые на десктопе видны.

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <button class="form-plans__delete" type="button" aria-label="Закрыть"></button>
Это поле ввода read-only, и для каждого поля есть функционал с выпадашкой и поиском страны, а не только для открытого.

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <button class="form-plans__delete" type="button" aria-label="Закрыть"></button>
По типу жёлтых фильтров в каталоге

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <button class="form-plans__delete" type="button" aria-label="Закрыть"></button>
Кнопка не Закрыть, а Удалить)

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <button class="form-plans__delete" type="button" aria-label="Закрыть"></button>
Список отсюда лучше вообще выпилить, засоряет разметку здесь. Каждая такая выпадашка для выбора страны - отдельный блок. И группа этих выпадашек тоже отдельный блок, в него входит ещё кнопка Добавить страну.

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <button class="form-plans__delete" type="button" aria-label="Закрыть"></button>
Выберите страну - плейсхолдер в поле, который сменяется на значение (через js, мы не реализуем это)

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +            <p class="form-plans__text">Наконец, расскажите о своих планахвремяпровождения. Можно писать в свободной
Пробел пропустила после "о своиз планах"

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +            <ul class="form-plans__action-list">
Тут тоже список - это избыточная разметка. Вообще списки в формах считается bad practice, так как засоряет и без того сложную разметку форм. Если нужна обёртка, просто на див замени.

2020-08-28 09:49 UTC, arctic-pie commented on form.html
> +                <h4 class="form-plans__action-title">Босния и Герцеговина</h4>
Это ж лейбл

2020-08-28 09:49 UTC, arctic-pie commented on index.html
> +        <button class="registration__btn" type="submit">
У тега button по умолчанию занчение атрибута type - это submit, по-этому не обязательно указывать.

2020-08-28 09:49 UTC, arctic-pie commented on index.html
> +      <ul class="registration__list user-nav">
Тут тоже список избыточен. Список предполагает, что элементов должно быть больше 1 шт. Если я решаю оставить в качестве контактов только номер телефона и почту убрать, помашет ручкой избыточная разметка.

2020-08-28 09:49 UTC, arctic-pie commented on index.html
> +            <span class="user-nav__text">Телефон 8 800 555-86-28</span>
А зачем тут слова Телефон и Электронный адрес?

2020-08-28 09:49 UTC, arctic-pie commented on index.html
> +        <button class="registration__btn" type="submit">
И кнопка эта называется просто Регистрация в десктопной версии

2020-08-28 11:12 UTC, Palladii commented on catalog.html
> +  </section>
Поправила

2020-08-28 11:46 UTC, Palladii commented on catalog.html
> +  <section class="filter-country">
Поправила

2020-08-28 11:47 UTC, Palladii commented on catalog.html
> +      <button class="filter__btn" type="button" aria-label="Открыть или закрыть"></button>
Поправила

2020-08-28 12:15 UTC, Palladii commented on catalog.html
> +            <a class="filter-traveler__btn" href="#">хобби</a>
Поправила

2020-08-28 12:25 UTC, Palladii commented on catalog.html
> +      <form class="filter-traveler" action="https://echo.htmlacademy.ru" method="GET">
Поправила

2020-08-28 13:10 UTC, Palladii commented on catalog.html
> +              <input class="filter-traveler__control" type="checkbox" id="gym" name="gym" checked>
Поправила

2020-08-28 13:14 UTC, Palladii commented on catalog.html
> +              </label>
Поправила

2020-08-28 14:13 UTC, Palladii commented on form.html
> +  </section>
Поправила

2020-08-28 14:17 UTC, Palladii commented on form.html
> +  <section class="profile__card card">
Поправила

2020-08-28 14:21 UTC, Palladii commented on form.html
> +          <h2 class="plans__country">Франция, Италия</h2>
Поправила

2020-08-28 14:22 UTC, Palladii commented on form.html
> +            <a class="markers__btn" href="#" aria-label="шаг 1"></a>
Добавила

2020-08-28 14:29 UTC, Palladii commented on form.html
> +              поездку<br>и ее предполагаемую<br>длительность.</p>
Поправила

2020-08-28 14:35 UTC, Palladii commented on form.html
> +                </label>
Поправила

2020-08-28 14:39 UTC, Palladii commented on form.html
> +            <p class="form-plans">Укажите предпочтительное<br>количество попутчиков, которых<br>вы хотели бы позвать в
Поправила

2020-08-28 14:51 UTC, Palladii commented on index.html
> +            <span class="user-nav__text">Телефон 8 800 555-86-28</span>
Поправила

2020-08-28 14:55 UTC, Palladii commented on index.html
> +      <ul class="registration__list user-nav">
Поправила

2020-08-28 14:58 UTC, Palladii commented on index.html
> +        <button class="registration__btn" type="submit">
Поправила

2020-08-28 15:02 UTC, Palladii commented on form.html
> +                <h4 class="form-plans__action-title">Босния и Герцеговина</h4>
Поправила

2020-08-28 15:04 UTC, Palladii commented on form.html
> +            <ul class="form-plans__action-list">
Поправила

2020-08-28 15:06 UTC, Palladii commented on form.html
> +            <p class="form-plans__text">Наконец, расскажите о своих планахвремяпровождения. Можно писать в свободной
Так в разметке, поправила

2020-08-28 15:10 UTC, Palladii commented on form.html
> +                <input class="form-plans__control-checkbox" type="checkbox" name="checkbox" id="checkbox"
Поправила

2020-08-29 10:05 UTC, Palladii commented on form.html
> +                <th class="form__day-name form__day-name--red">В</th>
Поправила

2020-08-29 10:09 UTC, Palladii commented on form.html
> +              <caption class="calendar__mounths">Март 2019</caption>
Поправила

2020-08-29 10:11 UTC, Palladii commented on form.html
> +            <a class="form-plans__next button" href="form.html#step-2">Следующий шаг</a>
Поправила

2020-08-29 10:12 UTC, Palladii commented on form.html
> +          <div class="container--narrow">
Поправила

2020-08-29 10:13 UTC, Palladii commented on form.html
> +          <div class="container--narrow">
Поправила

2020-08-29 10:25 UTC, Palladii commented on form.html
> +              несколько.</p>
Поправила

2020-08-29 11:17 UTC, Palladii commented on form.html
> +                <button class="form-plans__delete" type="button" aria-label="Закрыть"></button>
Поправила

2020-08-29 11:23 UTC, Palladii commented on form.html
> +              </div>
Поправила

2020-08-30 11:35 UTC, arctic-pie approved these changes

2020-08-30 16:50 UTC, merged