Начинаем верстать адаптивные сетки
htmlacademy-adaptive/476339-pognali-20 pull request #5
Opened 2020-08-20 14:05 UTC by Palladii

---
:mortar_board: [Начинаем верстать адаптивные сетки](https://up.htmlacademy.ru/adaptive/20/user/476339/tasks/8)

:boom: https://htmlacademy-adaptive.github.io/476339-pognali-20/5/

2020-09-03 19:52 UTC, arctic-pie requested changes

2020-09-03 19:52 UTC, arctic-pie commented on source/form.html
> +    <div class="footer-wrapper">
Блок/элемент?

2020-09-03 19:52 UTC, arctic-pie commented on source/form.html
> +        <span class="">Логотип Погнали?</span>
Тут что-то явно потеряно. Закрывающий тег ссылки, например

2020-09-03 19:52 UTC, arctic-pie commented on source/index.html
> -      </nav>
А чего кнопки в мейн то вернутся?

2020-09-03 19:52 UTC, arctic-pie commented on source/index.html
> +                <h3 class="direction__country direction__country">Таиланд</h3>
А зачем классдублируется?

2020-09-03 19:52 UTC, arctic-pie commented on source/sass/blocks/container.scss
> +    width: 1320px;
Тут явно закрывающих скобок недостаёт

2020-09-04 12:49 UTC, Palladii commented on source/catalog.html
> +          <a class="site-nav__link" href="form.html#about-service">О сервисе</a>
Поправила

2020-09-04 12:50 UTC, Palladii commented on source/form.html
> +          <a class="site-nav__link" href="form.html#about-service">О сервисе</a>
+

2020-09-04 12:52 UTC, Palladii commented on source/form.html
> +    <div class="footer-wrapper">
Поправила

2020-09-04 12:54 UTC, Palladii commented on source/form.html
> +        <span class="">Логотип Погнали?</span>
Сейчас все ок

2020-09-04 12:55 UTC, Palladii commented on source/index.html
> -      </nav>
+

2020-09-04 12:57 UTC, Palladii commented on source/index.html
> +                <h3 class="direction__country direction__country">Таиланд</h3>
+

2020-09-04 12:57 UTC, Palladii commented on source/index.html
> +                <h3 class="direction__country direction__country">Таиланд</h3>
Поправила

2020-09-04 12:57 UTC, Palladii commented on source/index.html
> -      </nav>
Поправила

2020-09-04 12:58 UTC, Palladii commented on source/sass/blocks/container.scss
> +    width: 1320px;
Поправила

2020-09-05 07:06 UTC, merged